kind: pipeline
type: docker
name: haiti-framework

steps:

  - name: publish
    image: maven:3.8.4-openjdk-11
    commands:
      - echo ${GPG_PRIVATE_KEY} >> gpg.key
      - echo ${TEST} >> test.key
      - cat test.key
      - echo "${MAVEN_SETTINGS}" >> maven-settings.xml
      - gpg --pinentry-mode loopback --passphrase ${GPG_PASSPHRASE} --import gpg.key
      - mvn --settings maven-settings.xml -U -P ossrh,release clean deploy

trigger:
#  ref:
#    - refs/tags/v.*.*.*