kind: pipeline
type: docker
name: haiti-framework

steps:

  - name: publish
    image: maven:3.8.4-openjdk-11
    environment:
      GPG_PRIVATE_KEY:
        from_secret: GPG_PRIVATE_KEY
      MAVEN_SETTINGS:
        from_secret: MAVEN_SETTINGS
      GPG_PASSPHRASE:
        from_secret: GPG_PASSPHRASE
    commands:
      - gpg --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --import $GPG_PRIVATE_KEY
      - mvn --settings $MAVEN_SETTINGS -U -P ossrh,release clean deploy

trigger:
#  ref:
#    - refs/tags/v.*.*.*