kind: pipeline
type: docker
name: haiti-framework

steps:

  - name: publish maven central
    image: maven:3.8.6-eclipse-temurin-17
    volumes:
      - name: m2
        path: /root/.m2/repository
    environment:
      GPG_PRIVATE_KEY:
        from_secret: GPG_PRIVATE_KEY
      MAVEN_SETTINGS:
        from_secret: MAVEN_SETTINGS
      GPG_PASSPHRASE:
        from_secret: GPG_PASSPHRASE
    commands:
      - echo "$GPG_PRIVATE_KEY" >> gpg.key
      - echo "$MAVEN_SETTINGS" >> maven-settings.xml
      - gpg --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --import gpg.key
      - mvn --settings maven-settings.xml -T 1C -U -P ossrh,release clean deploy

trigger:
  ref:
    - master

volumes:
  - name: m2
    host:
      path: /drone/volume/m2