kind: pipeline
type: docker
name: haiti-framework

steps:
  - name: package
    image: maven:3.8.6-eclipse-temurin-17
    volumes:
      - name: m2
        path: /root/.m2
    commands:
      - mvn -Dmaven.repo.local=/drone/.m2/repository -U clean package

trigger:
  branch:
    - master
#  ref:
#    - refs/tags/v.*.*.*

volumes:
  - name: m2
    host:
      path: ${PATH_MAVEN_M2}