image: maven:3.8.4-openjdk-11
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - /^release-.*$/

  before_script:
    - export GPG_TTY=$(tty)
    - gpg --import $GPG_PRIVATE_KEY
  script:
    - 'mvn --settings $MAVEN_SETTINGS -U -P ossrh,release clean deploy'
  artifacts:
    paths:
      - backend/target/*.jar